---
title: "FinalData"
author: "Josephine Decker"
date: "2023-11-13"
output: html_document
---
### Prompt1

```{r}
library(tidyverse)



finaldata <- read_csv("finalSet.csv")
```

```{r}
finaldata%>%
  count(PercentageNA)
```

```{r}
NA70_sub<- finaldata%>%
  filter(PercentageNA < 70, PercentageNA > 0)

NA70_sub

NA70_sub%>%
  count(PercentageNA)
```


```{r}
set.seed(12345)

train <- 2/3
test <- 1/3

ns <- nrow(NA70_sub)
ntrain <- round(train * ns)
ntest <- ns - ntrain

trainI <- sample(1:ns, ntrain)

train_data <- NA70_sub[trainI, ] 
test_data <- NA70_sub[-trainI, ]

view(train_data)
view(test_data)


#file_path <- "train_data1.csv"
#write.csv(train_data, file = file_path, row.names = FALSE)

#file_path <- "test_data1.csv"
#write.csv(test_data, file = file_path, row.names = FALSE)
```

```{r}
library(dplyr)

train_data <- train_data %>%
  filter(!is.na(s_dep_1_sad) & !is.na(s_dep_2_miserable_daily) & !is.na(s_dep_3_miserable_mostly) & !is.na(s_dep_7_irritable) & !is.na(s_dep_8_irritable_daily) & !is.na(s_dep_9_irratable_mostly) & !is.na(s_dep_13_anhedonia) & !is.na(s_dep_14_anhedonia_daily) & !is.na(s_dep_15_anhedonia_mostly) & !is.na(s_dep_18a_tired) & !is.na(s_dep_18b_appetite) & !is.na(s_dep_18c_weight) & !is.na(s_dep_18d_insomnia) & !is.na(s_dep_18e_hypersomnia) & !is.na(s_dep_18f_agitation) & !is.na(s_dep_18g_worthless) & !is.na(s_dep_18h_concentration) & !is.na(s_dep_5_miserable_duration) & !is.na(s_dep_11_irritable_duration) & !is.na(s_dep_16_anhedonia_duration) & !is.na(s_dep_20a_impact_family) & !is.na(s_dep_20b_impact_friendships) & !is.na(s_dep_20c_impact_school_work) & !is.na(s_dep_20d_impact_leisure) & !is.na(s_dep_4_miserable_cheered_up) & !is.na(s_dep_19_distress))
```

```{r}
test_data <- test_data %>%
  filter(!is.na(s_dep_1_sad) & !is.na(s_dep_2_miserable_daily) & !is.na(s_dep_3_miserable_mostly) & !is.na(s_dep_7_irritable) & !is.na(s_dep_8_irritable_daily) & !is.na(s_dep_9_irratable_mostly) & !is.na(s_dep_13_anhedonia) & !is.na(s_dep_14_anhedonia_daily) & !is.na(s_dep_15_anhedonia_mostly) & !is.na(s_dep_18a_tired) & !is.na(s_dep_18b_appetite) & !is.na(s_dep_18c_weight) & !is.na(s_dep_18d_insomnia) & !is.na(s_dep_18e_hypersomnia) & !is.na(s_dep_18f_agitation) & !is.na(s_dep_18g_worthless) & !is.na(s_dep_18h_concentration) & !is.na(s_dep_5_miserable_duration) & !is.na(s_dep_11_irritable_duration) & !is.na(s_dep_16_anhedonia_duration) & !is.na(s_dep_20a_impact_family) & !is.na(s_dep_20b_impact_friendships) & !is.na(s_dep_20c_impact_school_work) & !is.na(s_dep_20d_impact_leisure) & !is.na(s_dep_4_miserable_cheered_up) & !is.na(s_dep_19_distress))
```


```{r}
test1 <- read_csv("test_data.csv")
train1 <- read_csv("train_data.csv")
```


```{r}
Train_Data.70na<- rbind(train1,train_data)

summary(Train_Data.70na$min_age)
```

```{r}
Test_Data.70na<- rbind(test1,test_data)

summary(Test_Data.70na$min_age)
```

```{r}
file_path <- "train_data.70na.csv"
write.csv(Train_Data.70na, file = file_path, row.names = FALSE)

file_path <- "test_data.70na.csv"
write.csv(Test_Data.70na, file = file_path, row.names = FALSE)
```


```{r}
view(Train_Data.70na)
view(Test_Data.70na)
```

### Prompt 2

```{r}
library(tidyverse)



finaldata <- read_csv("finalSet.csv")
```

```{r}
finaldata%>%
  count(PercentageNA)
```

```{r}
NA70_sub<- finaldata%>%
  filter(PercentageNA < 70, PercentageNA > 0)

NA70_sub

NA70_sub%>%
  count(PercentageNA)
```


```{r}
set.seed(12345)

train <- 2/3
test <- 1/3

ns <- nrow(NA70_sub)
ntrain <- round(train * ns)
ntest <- ns - ntrain

trainI <- sample(1:ns, ntrain)

train_data <- NA70_sub[trainI, ] 
test_data <- NA70_sub[-trainI, ]

view(train_data)
view(test_data)


#file_path <- "train_data1.csv"
#write.csv(train_data, file = file_path, row.names = FALSE)

#file_path <- "test_data1.csv"
#write.csv(test_data, file = file_path, row.names = FALSE)
```

```{r}
library(dplyr)

train_data <- train_data %>%
  filter(!is.na(s_gad_4a_past_behaviour) & !is.na(s_gad_4b_school_work) & !is.na(s_gad_4c_disasters_accidents) & !is.na(s_gad_4d_own_health) & !is.na(s_gad_4e_bad_things_others) & !is.na(s_gad_4f_the_future) & !is.na(s_gad_4g_keeping_friends) & !is.na(s_gad_4h_death) & !is.na(s_gad_4i_bullied) & !is.na(s_gad_4j_appearance_weight) & !is.na(s_gad_6_worried_most_days) & !is.na(s_gad_7_worry_difficult_control) & !is.na(s_gad_3_excessive_worry))
```

```{r}
test_data <- test_data %>%
  filter(!is.na(s_gad_4a_past_behaviour) & !is.na(s_gad_4b_school_work) & !is.na(s_gad_4c_disasters_accidents) & !is.na(s_gad_4d_own_health) & !is.na(s_gad_4e_bad_things_others) & !is.na(s_gad_4f_the_future) & !is.na(s_gad_4g_keeping_friends) & !is.na(s_gad_4h_death) & !is.na(s_gad_4i_bullied) & !is.na(s_gad_4j_appearance_weight) & !is.na(s_gad_6_worried_most_days) & !is.na(s_gad_7_worry_difficult_control) & !is.na(s_gad_3_excessive_worry))
```


```{r}
test1 <- read_csv("test_data.csv")
train1 <- read_csv("train_data.csv")
```


```{r}
Train_Data2.70na<- rbind(train1,train_data)

summary(Train_Data.70na$min_age)
```

```{r}
Test_Data2.70na<- rbind(test1,test_data)

summary(Test_Data.70na$min_age)
```

```{r}
file_path <- "train_data2.70na.csv"
write.csv(Train_Data2.70na, file = file_path, row.names = FALSE)

file_path <- "test_data2.70na.csv"
write.csv(Test_Data2.70na, file = file_path, row.names = FALSE)
```


```{r}
view(Train_Data2.70na)
view(Test_Data2.70na)
```

```{r}
prompt2_questions <- Train_Data2.70na %>%
  select(s_gad_4a_past_behaviour,s_gad_4b_school_work, s_gad_4c_disasters_accidents, s_gad_4d_own_health, s_gad_4e_bad_things_others, s_gad_4f_the_future, s_gad_4g_keeping_friends, s_gad_4h_death, s_gad_4i_bullied, s_gad_4j_appearance_weight, s_gad_6_worried_most_days, s_gad_7_worry_difficult_control, s_gad_3_excessive_worry)
```

```{r}
prompt1_questions <- Train_Data.70na %>%
  select(s_dep_1_sad, s_dep_2_miserable_daily, s_dep_3_miserable_mostly, s_dep_7_irritable, s_dep_8_irritable_daily, s_dep_9_irratable_mostly, s_dep_13_anhedonia, s_dep_14_anhedonia_daily, s_dep_15_anhedonia_mostly, s_dep_18a_tired, s_dep_18b_appetite, s_dep_18c_weight, s_dep_18d_insomnia, s_dep_18e_hypersomnia, s_dep_18f_agitation, s_dep_18g_worthless, s_dep_18h_concentration, s_dep_5_miserable_duration, s_dep_11_irritable_duration, s_dep_16_anhedonia_duration, s_dep_20a_impact_family, s_dep_20b_impact_friendships, s_dep_20c_impact_school_work, s_dep_20d_impact_leisure, s_dep_4_miserable_cheered_up, s_dep_19_distress)
```


```{r}
file_path <- "prompt1_questions.csv"
write.csv(prompt1_questions, file = file_path, row.names = FALSE)

file_path <- "prompt2_questions.csv"
write.csv(prompt2_questions, file = file_path, row.names = FALSE)
```



```{r}
set.seed(12345)

train <- 2/3
test <- 1/3

ns <- nrow(finaldata)
ntrain <- round(train * ns)
ntest <- ns - ntrain

trainI <- sample(1:ns, ntrain)

train_data <- finaldata[trainI, ] 
test_data <- finaldata[-trainI, ]

view(train_data)
view(test_data)
```

```{r}
library(dplyr)

train_data1 <- train_data %>%
  filter(!is.na(s_gad_4a_past_behaviour) & !is.na(s_gad_4b_school_work) & !is.na(s_gad_4c_disasters_accidents) & !is.na(s_gad_4d_own_health) & !is.na(s_gad_4e_bad_things_others) & !is.na(s_gad_4f_the_future) & !is.na(s_gad_4g_keeping_friends) & !is.na(s_gad_4h_death) & !is.na(s_gad_4i_bullied) & !is.na(s_gad_4j_appearance_weight) & !is.na(s_gad_6_worried_most_days) & !is.na(s_gad_7_worry_difficult_control) & !is.na(s_gad_3_excessive_worry))
```

```{r}
test_data1 <- test_data %>%
  filter(!is.na(s_gad_4a_past_behaviour) & !is.na(s_gad_4b_school_work) & !is.na(s_gad_4c_disasters_accidents) & !is.na(s_gad_4d_own_health) & !is.na(s_gad_4e_bad_things_others) & !is.na(s_gad_4f_the_future) & !is.na(s_gad_4g_keeping_friends) & !is.na(s_gad_4h_death) & !is.na(s_gad_4i_bullied) & !is.na(s_gad_4j_appearance_weight) & !is.na(s_gad_6_worried_most_days) & !is.na(s_gad_7_worry_difficult_control) & !is.na(s_gad_3_excessive_worry))
```


```{r}
nrow(train_data2)
```



```{r}
library(dplyr)

train_data2 <- train_data %>%
  filter(!is.na(s_dep_1_sad) & !is.na(s_dep_2_miserable_daily) & !is.na(s_dep_3_miserable_mostly) & !is.na(s_dep_7_irritable) & !is.na(s_dep_8_irritable_daily) & !is.na(s_dep_9_irratable_mostly) & !is.na(s_dep_13_anhedonia) & !is.na(s_dep_14_anhedonia_daily) & !is.na(s_dep_15_anhedonia_mostly) & !is.na(s_dep_18a_tired) & !is.na(s_dep_18b_appetite) & !is.na(s_dep_18c_weight) & !is.na(s_dep_18d_insomnia) & !is.na(s_dep_18e_hypersomnia) & !is.na(s_dep_18f_agitation) & !is.na(s_dep_18g_worthless) & !is.na(s_dep_18h_concentration) & !is.na(s_dep_5_miserable_duration) & !is.na(s_dep_11_irritable_duration) & !is.na(s_dep_16_anhedonia_duration) & !is.na(s_dep_20a_impact_family) & !is.na(s_dep_20b_impact_friendships) & !is.na(s_dep_20c_impact_school_work) & !is.na(s_dep_20d_impact_leisure) & !is.na(s_dep_4_miserable_cheered_up) & !is.na(s_dep_19_distress))
```

```{r}
test_data2 <- test_data %>%
  filter(!is.na(s_dep_1_sad) & !is.na(s_dep_2_miserable_daily) & !is.na(s_dep_3_miserable_mostly) & !is.na(s_dep_7_irritable) & !is.na(s_dep_8_irritable_daily) & !is.na(s_dep_9_irratable_mostly) & !is.na(s_dep_13_anhedonia) & !is.na(s_dep_14_anhedonia_daily) & !is.na(s_dep_15_anhedonia_mostly) & !is.na(s_dep_18a_tired) & !is.na(s_dep_18b_appetite) & !is.na(s_dep_18c_weight) & !is.na(s_dep_18d_insomnia) & !is.na(s_dep_18e_hypersomnia) & !is.na(s_dep_18f_agitation) & !is.na(s_dep_18g_worthless) & !is.na(s_dep_18h_concentration) & !is.na(s_dep_5_miserable_duration) & !is.na(s_dep_11_irritable_duration) & !is.na(s_dep_16_anhedonia_duration) & !is.na(s_dep_20a_impact_family) & !is.na(s_dep_20b_impact_friendships) & !is.na(s_dep_20c_impact_school_work) & !is.na(s_dep_20d_impact_leisure) & !is.na(s_dep_4_miserable_cheered_up) & !is.na(s_dep_19_distress))
```



```{r}
conf_matrix <- table(predicted = P1_Final$openai_Bo5_answer, observed = P1_Final$s_dep_19_distress)
print(conf_matrix)
(6 + 40) / (6 + 6 + 1 + 14 + 40) #accuracy 68.66%
6 / (6 + 6) #Precision of 2(a medium amount of distress) 50%
40 / (40 + 1) #Precision of 3(a great deal) 97%
6 / (6 + 1) #Recall for 2(a medium amount of distress) 85.7%
40 / (40 + 14) #Recall for 3(a great deal) 74%

```




```{r}
prompt1<-read_csv("train_data.70na.csv")
prompt2<-read_csv("train_data2.70na.csv")
```

```{r}
plot1<- ggplot(prompt2,aes(SEX, fill = SEX))+
  geom_bar(stat = "count")+
  geom_text(
    stat = "count",
    aes(label = stat(count)),
    position = position_stack(vjust = 0.5),
    color = "black",
    size = 3
  )

plot1

sex_colors <- c("MALE" = "darkseagreen", "FEMALE" = "coral1")

# Modify the plot to use the specified colors
plot1 <- plot1 + scale_fill_manual(values = sex_colors)

# Print the plot
print(plot1)


```

```{r}
plot2<-ggplot(prompt2,aes(Participant_Type2, fill = Participant_Type2))+
  geom_bar(stat = "count")+
  facet_wrap(~ min_age)+
  xlab("Participant Type")+
    geom_text(
    stat = "count",
    aes(label = stat(count)),
    position = position_stack(vjust = 0.5),
    color = "black",
    size = 3
  )


PartType_colors <- c("HV" = "darkseagreen3", "MDD" = "cadetblue3", "Anxious" = "aquamarine3")

# Modify the plot to use the specified colors
plot2 <- plot2 + scale_fill_manual(values = PartType_colors)

# Print the plot
print(plot2)

  
```
















Prompt 1
```{r}
P1_1 <- read_csv("openai_traindata_Prompt1_1.csv")
P1_Bo5 <- read_csv("openai_traindata_Prompt1_Bo5.csv")
P1_Exp <- read_csv("openai_traindata_Prompt1_Explanation.csv")

P1_1 <- P1_1%>%
  rename(openai_1_answer = openai_answer)
P1_Bo5 <- P1_Bo5%>%
  rename(openai_Bo5_answer = openai_final_answer)%>%
  select(openai_Bo5_answer)
P1_Exp <- P1_Exp%>%
  rename(openai_Exp_answer = openai_answer)%>%
  select(openai_Exp_answer, openai_answer_explanation)

P1_Final <- cbind(P1_1,P1_Bo5,P1_Exp)

P1_Final <- P1_Final%>%
  select(!"Unnamed: 0")

P1_Final <- P1_Final%>%
  rename(Subject = ...1)

P1_Final <- P1_Final %>%
  select(Subject, SEX, min_age, Participant_Type2, s_dep_1_sad, s_dep_2_miserable_daily, s_dep_3_miserable_mostly, s_dep_7_irritable, s_dep_8_irritable_daily, s_dep_9_irratable_mostly, s_dep_13_anhedonia, s_dep_14_anhedonia_daily, s_dep_15_anhedonia_mostly, s_dep_18a_tired, s_dep_18b_appetite, s_dep_18c_weight, s_dep_18d_insomnia, s_dep_18e_hypersomnia, s_dep_18f_agitation, s_dep_18g_worthless, s_dep_18h_concentration, s_dep_5_miserable_duration, s_dep_11_irritable_duration, s_dep_16_anhedonia_duration, s_dep_20a_impact_family, s_dep_20b_impact_friendships, s_dep_20c_impact_school_work, s_dep_20d_impact_leisure, s_dep_4_miserable_cheered_up, s_dep_19_distress,openai_1_answer, openai_Bo5_answer, openai_Exp_answer)

#view(P1_Final)


columns_to_change1 <- c("s_dep_1_sad", "s_dep_2_miserable_daily", "s_dep_3_miserable_mostly", "s_dep_7_irritable", "s_dep_8_irritable_daily", "s_dep_9_irratable_mostly", "s_dep_13_anhedonia", "s_dep_14_anhedonia_daily", "s_dep_15_anhedonia_mostly", "s_dep_18a_tired", "s_dep_18b_appetite", "s_dep_18c_weight", "s_dep_18d_insomnia", "s_dep_18e_hypersomnia", "s_dep_18f_agitation", "s_dep_18g_worthless", "s_dep_18h_concentration")  

columns_to_change2 <- c("s_dep_5_miserable_duration", "s_dep_11_irritable_duration", "s_dep_16_anhedonia_duration")

columns_to_change3 <- c("s_dep_20a_impact_family", "s_dep_20b_impact_friendships", "s_dep_20c_impact_school_work", "s_dep_20d_impact_leisure", "s_dep_19_distress", "openai_1_answer", "openai_Bo5_answer", "openai_Exp_answer")



P1_Final <- P1_Final %>%
  mutate(across(all_of(columns_to_change1), ~recode(., "no" = 0, "yes" = 1)))%>%
  mutate(across(all_of(columns_to_change2), ~recode(., "less than 2 weeks" = 0, "2 weeks or more" = 1)))%>%
  mutate(across(all_of(columns_to_change3), ~recode(., "not at all" = 0, "a little" = 1, "a medium amount" = 2, "a great deal" = 3)))%>%
  mutate(s_dep_4_miserable_cheered_up = recode(s_dep_4_miserable_cheered_up, "easily" = 0, "with difficulty/only briefly" = 1, "not at all" = 2))%>%
  mutate(SEX = recode(SEX, "MALE" = 0, "FEMALE" = 1))%>%
  mutate(Participant_Type2 = recode(Participant_Type2, "MDD" = 0, "HV" = 1, "Anxious" = 2))


view(P1_Final)
```

Looking at Bo5 and Explanation
```{r}
result_P1 <- t.test(P1_Final$openai_Bo5_answer, P1_Final$openai_Exp_answer, paired = TRUE)

print(result_P1)


mbo5<- mean(P1_Final$openai_Bo5_answer)
mexp<- mean(P1_Final$openai_Exp_answer)

mbo5-mexp

```

Looking at 1 and Explanation
```{r}
result_P1b <- t.test(P1_Final$openai_1_answer, P1_Final$openai_Exp_answer, paired = TRUE)

print(result_P1b)

```








Prompt 2
```{r}
P2_1 <- read_csv("openai_traindata_Prompt2_1.csv")
P2_Bo5 <- read_csv("openai_traindata_Prompt2_Bo5.csv")
P2_Exp <- read_csv("openai_traindata_Prompt2_Explanation.csv")

P2_1 <- P2_1%>%
  rename(openai_1_answer = openai_answer)
P2_Bo5 <- P2_Bo5%>%
  rename(openai_Bo5_answer = openai_final_answer)%>%
  select(openai_Bo5_answer)
P2_Exp <- P2_Exp%>%
  rename(openai_Exp_answer = openai_answer)%>%
  select(openai_Exp_answer, openai_answer_explanation)

P2_1 <- P2_1[-76, ]

P2_Final <- cbind(P2_1,P2_Bo5,P2_Exp)

#view(P2_Final)
P2_Final <- P2_Final[, -2]
P2_Final <- P2_Final[, -2]
P2_Final <- P2_Final%>%
  rename(Subject = ...1)

P2_Final <- P2_Final%>%
  select(Subject, SEX, min_age, Participant_Type2, s_gad_4a_past_behaviour,s_gad_4b_school_work, s_gad_4c_disasters_accidents, s_gad_4d_own_health, s_gad_4e_bad_things_others, s_gad_4f_the_future, s_gad_4g_keeping_friends, s_gad_4h_death, s_gad_4i_bullied, s_gad_4j_appearance_weight, s_gad_6_worried_most_days, s_gad_7_worry_difficult_control, s_gad_3_excessive_worry, openai_1_answer, openai_Bo5_answer, openai_Exp_answer)

#view(P2_Final)

columns_to_change1 <- c("s_gad_4a_past_behaviour", "s_gad_4b_school_work" , "s_gad_4c_disasters_accidents", "s_gad_4d_own_health", "s_gad_4e_bad_things_others", "s_gad_4f_the_future" ,"s_gad_4g_keeping_friends" , "s_gad_4h_death", "s_gad_4i_bullied", "s_gad_4j_appearance_weight")  

columns_to_change2 <- c("s_gad_6_worried_most_days", "s_gad_7_worry_difficult_control")

columns_to_change3 <- c("s_gad_3_excessive_worry", "openai_1_answer", "openai_Bo5_answer", "openai_Exp_answer")


P2_Final <- P2_Final %>%
  mutate(across(all_of(columns_to_change1), ~recode(., "no more than others" = 0, "a little more than others" = 1, "a lot more than others" = 2)))%>%
  mutate(across(all_of(columns_to_change2), ~recode(., "no" = 0, "yes" = 1)))%>%
  mutate(across(all_of(columns_to_change3), ~recode(., "no" = 0, "perhaps" = 1, "definitely" = 2)))%>%
  mutate(SEX = recode(SEX, "MALE" = 0, "FEMALE" = 1))%>%
  mutate(Participant_Type2 = recode(Participant_Type2, "MDD" = 0, "HV" = 1, "Anxious" = 2))

view(P2_Final)
```


Looking at Bo5 and Explanation
```{r}
result_P2 <- t.test(P2_Final$openai_Bo5_answer, P2_Final$openai_Exp_answer, paired = TRUE)

print(result_P2)


```

Looking at 1 and Explanation
```{r}
result_P2b <- t.test(P2_Final$openai_1_answer, P2_Final$openai_Exp_answer, paired = TRUE)

print(result_P2b)

```





### Prompt 1 Confusion Matrix

```{r}
conf_matrix <- table(predicted = P1_Final$openai_Bo5_answer, observed = P1_Final$s_dep_19_distress)
print(conf_matrix)
Acc <- ((6 + 40) / (6 + 6 + 1 + 14 + 40)) #accuracy 68.66%
P2<-(6 / (6 + 6)) #Precision of 2(a medium amount of distress) .50
R2<-(6 / (6 + 14)) #Recall for 2(a medium amount of distress) .30
F1_2 <- ((2)*((P2*R2)/(P2+R2))) # F1 class 2 = .38
P3 <-(40 / (40 + 14 +1)) #Precision of 3(a great deal ) .73
R3 <- (40 / (40 + 6)) #Recall for 3(a great deal ) .87
F1_3 <- ((2)*((P3*R3)/(P3+R3))) # F1 class 3  = .79





Acc
P2
R2
P3
R3
F1_2
F1_3

```

```{r}
conf_matrix <- table(predicted = P1_Final$openai_Exp_answer, observed = P1_Final$s_dep_19_distress)
print(conf_matrix)

Acc <- ((9 + 27) / (9 + 27 + 4 + 5 + 1 + 7 + 14)) #accuracy 53.7%
P1<-(9 / (9 + 14 + 1)) #Precision of 2(a medium amount of distress) .37
R1<-(9 / (9 + 4 + 7)) #Recall for 2(a medium amount of distress) .45
F1_1 <- ((2)*((P1*R1)/(P1+R1))) # F1 class 2 =  .41
P2 <-(27 / (7 + 27)) #Precision of 3(a great deal ) .79
R2 <- (27 / (14 + 27 + 5)) #Recall for 3(a great deal ) .59
F1_2 <- ((2)*((P2*R2)/(P2+R2))) # F1 class 3 = .68

Acc
P1
R1
P2
R2
F1_1
F1_2




```
```{r}
conf_matrix <- table(predicted = P1_Final$openai_1_answer, observed = P1_Final$s_dep_19_distress)
print(conf_matrix)


Acc <- ((6 + 40) / (6 + 6 + 1 + 14 + 40)) #accuracy 68.66%
P2<-(6 / (6 + 6 +1)) #Precision of 2(a medium amount of distress) .46
R2<-(6 / (6 + 14)) #Recall for 2(a medium amount of distress) .30
F1_2 <- ((2)*((P2*R2)/(P2+R2))) # F1 class 2 = .36
P3 <-(40 / (40 + 14)) #Precision of 3(a great deal ) .74
R3 <- (40 / (40 + 6)) #Recall for 3(a great deal ) .87
F1_3 <- ((2)*((P3*R3)/(P3+R3))) # F1 class 3  = .80

Acc
P2
R2
P3
R3
F1_2
F1_3
nrow(P1_Final)
```

### Prompt 2 Confusion Matrix

```{r}
conf_matrix <- table(predicted = P2_Final$openai_Bo5_answer, observed = P2_Final$s_gad_3_excessive_worry)
print(conf_matrix)

Acc <- ((15 + 33) / (15 + 33 + 16 + 1 + 9)) #accuracy 64%
Pd<-(15 / (15+16)) #Precision of 1 = .62
Rd<-(15 / (15+9)) #Recall for 1 =  .46
F1d <- ((2)*((Pd*Rd)/(Pd+Rd)))  # .53
Pw <-(33 / (33 + 9 + 1)) #Precision of 2 =  .77
Rw <- (33 / (33 + 16)) #Recall for 2 = .66
F1w <- ((2)*((Pw*Rw)/(Pw+Rw))) # .70

Acc
Pd
Rd
Pw
Rw
F1d
F1w
```

```{r}
conf_matrix <- table(predicted = P2_Final$openai_Exp_answer, observed = P2_Final$s_gad_3_excessive_worry)
print(conf_matrix)


Acc <- ((6 + 25) / (6 + 25 + 14 + 1 + 8 + 10 + 10)) #accuracy 42%
Pd<-(6 / (14+6)) #Precision of 1 = .30
Rd<-(6 / (6+8+10)) #Recall for 1 =  .25
F1d <- ((2)*((Pd*Rd)/(Pd+Rd)))  # .28
Pw <-(25 / (25 + 8 + 1)) #Precision of 2 =  .74
Rw <- (25 / (25 + 14 + 10)) #Recall for 2 = .51
F1w <- ((2)*((Pw*Rw)/(Pw+Rw))) # .60

Acc
Pd
Rd
Pw
Rw
F1d
F1w



```
```{r}
conf_matrix <- table(predicted = P2_Final$openai_1_answer, observed = P2_Final$s_gad_3_excessive_worry)
print(conf_matrix)


Acc <- ((6 + 25) / (6 + 25 + 14 + 1 + 8 + 10 + 10)) #accuracy 42%
Pd<-(6 / (14+6)) #Precision of 1 = .30
Rd<-(6 / (6+8+10)) #Recall for 1 =  .25
F1d <- ((2)*((Pd*Rd)/(Pd+Rd)))  # .28
Pw <-(25 / (25 + 8 + 1)) #Precision of 2 =  .74
Rw <- (25 / (25 + 14 + 10)) #Recall for 2 = .51
F1w <- ((2)*((Pw*Rw)/(Pw+Rw))) # .60

Acc
Pd
Rd
Pw
Rw
F1d
F1w
```



### Prompt 1

#### Bo5
```{r}
P1_Final$accuracy_Bo5 <- ifelse(P1_Final$s_dep_19_distress == P1_Final$openai_Bo5_answer, 1, 0)

P1_Final%>%
  count(accuracy_Bo5)
```
#### Explanation
```{r}
P1_Final$accuracy_Exp <- ifelse(P1_Final$s_dep_19_distress == P1_Final$openai_Exp_answer, 1, 0)

P1_Final%>%
  count(accuracy_Exp)
```

### Ran once

```{r}
P1_Final$accuracy_1 <- ifelse(P1_Final$s_dep_19_distress == P1_Final$openai_1_answer, 1, 0)

P1_Final%>%
  count(accuracy_1)
```

### Prompt 2

#### Bo5
```{r}
P2_Final$accuracy_Bo5 <- ifelse(P2_Final$s_gad_3_excessive_worry == P2_Final$openai_Bo5_answer, 1, 0)

P2_Final%>%
  count(accuracy_Bo5)
```
#### Explanation
```{r}
P2_Final$accuracy_Exp <- ifelse(P2_Final$s_gad_3_excessive_worry == P2_Final$openai_Exp_answer, 1, 0)

P2_Final%>%
  count(accuracy_Exp)
```

```{r}
P1_Final$diff_acc <- P1_Final$accuracy_Bo5 - P1_Final$accuracy_Exp

P1_Final
```


Bo5

```{r}

P1_Final$diff_acc <- P1_Final$accuracy_Bo5 - P1_Final$accuracy_Exp

n <- nrow(P1_Final)

mean_diff <- mean(P1_Final$diff_acc)


pop_var_diff <- var(P1_Final$diff_acc)

z <- ((mean_diff) - (0))/(sqrt((pop_var_diff)/n))
z

help(pnorm)

pnorm(z, lower.tail = FALSE)*2
```

```{r}
result <- t.test(P1_Final$accuracy_Bo5, P1_Final$accuracy_Exp, alternative = "two.sided", paired = TRUE)

print(result)

```


ran once
```{r}
P1_Final$diff_acc1 <- P1_Final$accuracy_1 - P1_Final$accuracy_Exp

n <- nrow(P1_Final)

mean_diff <- mean(P1_Final$diff_acc1)


pop_var_diff <- var(P1_Final$diff_acc1)

z <- ((mean_diff) - (0))/(sqrt((pop_var_diff)/n))
z
view(P1_Final)

pnorm(z, lower.tail = FALSE)*2

```

```{r}
result <- t.test(P1_Final$accuracy_1, P1_Final$accuracy_Exp, alternative = "two.sided", paired = TRUE)

print(result)

```



Prompt 2 z test
```{r}
P2_Final$diff_acc <- P2_Final$accuracy_Bo5 - P2_Final$accuracy_Exp

P2_Final
mean(P2_Final$diff_acc)

n <- nrow(P2_Final)

mean_diff <- mean(P2_Final$diff_acc)


pop_var_diff <- var(P2_Final$diff_acc)

z <- ((mean_diff) - (0))/(sqrt((pop_var_diff)/n))
z

pnorm(z, lower.tail = FALSE)*2


```

```{r}

result <- t.test(P2_Final$accuracy_Bo5, P2_Final$accuracy_Exp, alternative = "two.sided", paired = TRUE)

print(result)
```

```{r}
P1<- P1_Final%>%
  select(s_dep_19_distress, openai_1_answer, accuracy_1)

view(P1)

```

```{r}
P1_Final%>%
  count(s_dep_19_distress)

```

```{r}
P2_Final%>%
  count(s_gad_3_excessive_worry)
```
```{r}
nrow(prompt2)
```


```{r}
prompt1<-read_csv("train_data.70na.csv")
prompt2<-read_csv("train_data2.70na.csv")
prompt1T<-read_csv("test_data.70na.csv")
prompt2T<-read_csv("test_data2.70na.csv")



```

```{r}
nrow(prompt1)
nrow(prompt2)
nrow(prompt1T)
nrow(prompt2T)

```
```{r}
summary(prompt1$min_age)
summary(prompt1T$min_age)
```

```{r}
summary(prompt2$min_age)
summary(prompt2T$min_age)
```




